"""
Generates every chart in docs/assets/ from the live outputs of the ML pipeline.

Nothing here is drawn by hand or copied from a previous run. Each figure reads the parquet
and json that ml/detect_anomalies.py and ml/volume_monitor.py just wrote, so a chart in the
README cannot silently disagree with the numbers in the text -- if a metric moves, the
picture moves with it on the next run.

That is a deliberate choice about trust. A screenshot pasted into a README is unverifiable
and ages badly; a chart regenerated by `make charts` is neither.

Usage:
    python -m ml.charts
"""
from __future__ import annotations

import json
import os

import matplotlib
matplotlib.use("Agg")           # no display on CI or a headless box

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import FuncFormatter

ML_DIR = os.path.join("data", "ml")
OUT_DIR = os.path.join("docs", "assets")

# Palette. Dark slate background with a small number of saturated accents, chosen for
# legibility against both light and dark GitHub themes -- a chart that vanishes in dark mode
# is a chart nobody looks at.
BG = "#0d1117"
PANEL = "#161b22"
GRID = "#30363d"
TEXT = "#e6edf3"
MUTED = "#8b949e"
BLUE = "#58a6ff"
GREEN = "#3fb950"
AMBER = "#d29922"
RED = "#f85149"
PURPLE = "#bc8cff"

plt.rcParams.update({
    "figure.facecolor": BG,
    "axes.facecolor": PANEL,
    "savefig.facecolor": BG,
    "text.color": TEXT,
    "axes.labelcolor": TEXT,
    "axes.edgecolor": GRID,
    "xtick.color": MUTED,
    "ytick.color": MUTED,
    "grid.color": GRID,
    "font.size": 10,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "figure.dpi": 130,
})


def _style(ax, title: str, subtitle: str = "") -> None:
    ax.set_title(title, color=TEXT, pad=18 if subtitle else 10, loc="left")
    if subtitle:
        ax.text(0.0, 1.02, subtitle, transform=ax.transAxes,
                color=MUTED, fontsize=9, va="bottom")
    ax.grid(True, alpha=0.25, linewidth=0.6)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)


def _save(fig, name: str) -> str:
    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, name)
    fig.savefig(path, bbox_inches="tight", pad_inches=0.3)
    plt.close(fig)
    size = os.path.getsize(path) / 1024
    print(f"  {name:<34}{size:>7.0f} KB")
    return path


# --------------------------------------------------------------------------- 1
def chart_score_distribution(scored: pd.DataFrame, metrics: dict) -> None:
    """
    Anomaly score distribution, clean against defective, with the threshold drawn on.

    A log y-axis is essential rather than decorative. There are 199,500 clean rows and 162
    contextual anomalies; on a linear scale the anomalies are invisible, which is exactly
    the problem the chart exists to illustrate.
    """
    fig, ax = plt.subplots(figsize=(10, 5))

    clean = scored.loc[scored["defect_type"] == "CLEAN", "anomaly_score"]
    price = scored.loc[scored["defect_type"] == "CONTEXTUAL_PRICE", "anomaly_score"]
    qty = scored.loc[scored["defect_type"] == "CORRUPT_QUANTITY", "anomaly_score"]

    bins = np.linspace(scored["anomaly_score"].min(), scored["anomaly_score"].max(), 90)
    ax.hist(clean, bins=bins, color=BLUE, alpha=0.75, label=f"clean ({len(clean):,})")
    ax.hist(price, bins=bins, color=AMBER, alpha=0.95,
            label=f"contextual price ({len(price)})")
    ax.hist(qty, bins=bins, color=RED, alpha=0.95,
            label=f"corrupt quantity ({len(qty)})")

    thr = metrics["score_threshold"]
    ax.axvline(thr, color=PURPLE, linestyle="--", linewidth=1.6)
    ax.text(thr, ax.get_ylim()[1] * 0.45, f"  threshold\n  {thr:.3f}",
            color=PURPLE, fontsize=9, va="top")

    ax.set_yscale("log")
    ax.set_xlabel("isolation forest anomaly score  (higher = more anomalous)")
    ax.set_ylabel("rows  (log scale)")
    _style(ax, "Anomaly scores separate contextual price defects from clean rows",
           "Log scale, because 162 anomalies against 199,500 clean rows are otherwise "
           "invisible -- which is the whole problem")
    ax.legend(facecolor=PANEL, edgecolor=GRID, labelcolor=TEXT, framealpha=0.9)
    _save(fig, "ml_score_distribution.png")


# --------------------------------------------------------------------------- 2
def chart_rule_vs_model(metrics: dict) -> None:
    """
    The central result: which technique wins on which defect class.

    Grouped bars rather than a table because the reversal between the two panels is the
    finding, and a reversal is easier to see than to read.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)

    panels = [
        ("CORRUPT_QUANTITY", "Corrupt quantity — absolute violation",
         "quantity > 1e6 is exact. The model is strictly worse here."),
        ("CONTEXTUAL_PRICE", "Contextual price — relative violation",
         "No global threshold fits a catalogue of washers and pumps."),
    ]
    names = {
        "sql_rule_quantity_gt_1e6": "SQL rule\nquantity > 1e6",
        "sql_rule_unit_cost_p99.9": "SQL rule\nunit_cost p99.9",
        "isolation_forest": "Isolation\nForest",
    }

    for ax, (defect, title, sub) in zip(axes, panels):
        data = metrics["by_class"][defect]
        keys = list(names.keys())
        x = np.arange(len(keys))
        width = 0.27

        prec = [data[k]["precision"] for k in keys]
        rec = [data[k]["recall"] for k in keys]
        f1 = [data[k]["f1"] for k in keys]

        ax.bar(x - width, prec, width, label="precision", color=BLUE)
        ax.bar(x, rec, width, label="recall", color=GREEN)
        ax.bar(x + width, f1, width, label="F1", color=AMBER)

        for xi, vals in zip(x, zip(prec, rec, f1)):
            for off, v in zip((-width, 0, width), vals):
                if v > 0.02:
                    ax.text(xi + off, v + 0.02, f"{v:.2f}", ha="center",
                            color=TEXT, fontsize=8)

        ax.set_xticks(x)
        ax.set_xticklabels([names[k] for k in keys], fontsize=9)
        ax.set_ylim(0, 1.15)
        _style(ax, title, sub)

    axes[0].set_ylabel("score")
    axes[0].legend(facecolor=PANEL, edgecolor=GRID, labelcolor=TEXT,
                   framealpha=0.9, loc="upper right")
    fig.suptitle("Rules and models are not interchangeable",
                 color=TEXT, fontsize=15, fontweight="bold", x=0.09, ha="left", y=1.04)
    _save(fig, "ml_rule_vs_model.png")


# --------------------------------------------------------------------------- 3
def chart_pr_curve(pr: pd.DataFrame, metrics: dict) -> None:
    """
    Precision-recall curve with all three candidate operating points marked.

    PR rather than ROC: at a 0.08% positive rate, ROC looks flattering because the false
    positive rate is diluted by 199,500 easy negatives. PR does not let you hide that.
    """
    fig, ax = plt.subplots(figsize=(9, 6))

    ax.plot(pr["recall"], pr["precision"], color=BLUE, linewidth=2,
            label="isolation forest")

    price = metrics["by_class"]["CONTEXTUAL_PRICE"]
    ops = metrics["operating_points_contextual_price"]
    rule = price["sql_rule_unit_cost_p99.9"]

    points = [
        (rule["recall"], rule["precision"], RED, "o",
         f"SQL rule p99.9  (F1 {rule['f1']:.2f})"),
        (price["isolation_forest"]["recall"], price["isolation_forest"]["precision"],
         AMBER, "s", f"contamination {metrics['contamination']}  "
                     f"(F1 {price['isolation_forest']['f1']:.2f})"),
        (ops["best_f1_oracle"]["recall"], ops["best_f1_oracle"]["precision"],
         PURPLE, "D", f"best F1, oracle-tuned  (F1 {ops['best_f1_oracle']['f1']:.2f})"),
        (ops["alert_budget"]["recall"], ops["alert_budget"]["precision"],
         GREEN, "*", f"top-{ops['alert_budget']['budget']} alert budget  "
                     f"(precision {ops['alert_budget']['precision']:.2f})"),
    ]
    for r, p, colour, marker, label in points:
        ax.scatter([r], [p], color=colour, s=190 if marker == "*" else 110,
                   marker=marker, zorder=5, edgecolors=BG, linewidths=1.2, label=label)

    ap = price["isolation_forest"]["average_precision"]
    ax.set_xlabel("recall")
    ax.set_ylabel("precision")
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.05)
    _style(ax, f"Contextual price anomalies — average precision {ap:.3f}",
           "Four thresholds on one curve. Only the green star can be chosen without "
           "already knowing the answers.")
    ax.legend(facecolor=PANEL, edgecolor=GRID, labelcolor=TEXT,
              framealpha=0.9, loc="lower left", fontsize=9)
    _save(fig, "ml_pr_curve.png")


# --------------------------------------------------------------------------- 4
def chart_volume_monitor(daily: pd.DataFrame) -> None:
    """
    Daily row counts per subsidiary with the outage and spike marked.

    The outage is the point of the figure: three days at exactly zero for one company,
    which every row-level test in the project reports as healthy.

    Daily counts over 900 days are visually noisy, so incidents are highlighted with a
    full-height band rather than left to be spotted among the noise. A monitoring chart
    that requires squinting is not a monitoring chart.
    """
    companies = (
        daily[["company_key", "company_name"]]
        .drop_duplicates()
        .sort_values("company_key")
    )
    n = len(companies)

    fig, axes = plt.subplots(n, 1, figsize=(13, 1.75 * n), sharex=True)
    if n == 1:
        axes = [axes]

    for ax, (_, row) in zip(axes, companies.iterrows()):
        grp = daily[daily["company_key"] == row["company_key"]].sort_values("txn_date")

        drops = grp[(grp["is_anomaly"]) & (grp["direction"] == "DROP")]
        spikes = grp[(grp["is_anomaly"]) & (grp["direction"] == "SPIKE")]

        # Full-height bands first, so they sit behind the series.
        #
        # np.timedelta64 with an explicit unit rather than pd.Timedelta: this pandas build
        # routes every Timedelta construction through a generic numpy timedelta, which numpy
        # now deprecates. Being explicit about the unit sidesteps it and is clearer anyway.
        half = np.timedelta64(2, "D")
        for _, d in drops.iterrows():
            centre = pd.Timestamp(d["txn_date"])
            ax.axvspan(centre - half, centre + half, color=RED, alpha=0.22, zorder=0)
        for _, s in spikes.iterrows():
            centre = pd.Timestamp(s["txn_date"])
            ax.axvspan(centre - half, centre + half, color=AMBER, alpha=0.22, zorder=0)

        ax.plot(grp["txn_date"], grp["row_count"], color=BLUE,
                linewidth=0.5, alpha=0.5, zorder=2)
        ax.plot(grp["txn_date"], grp["expected"], color=TEXT,
                linewidth=1.3, alpha=0.85, zorder=3)

        ax.scatter(drops["txn_date"], drops["row_count"], color=RED, s=42,
                   zorder=6, edgecolors=BG, linewidths=0.7)
        ax.scatter(spikes["txn_date"], spikes["row_count"], color=AMBER, s=42,
                   zorder=6, edgecolors=BG, linewidths=0.7)

        # Company name inside the panel, which reads better than a rotated axis label.
        verdict = ""
        if not drops.empty:
            verdict += f"   {len(drops)} DROP"
        if not spikes.empty:
            verdict += f"   {len(spikes)} SPIKE"
        ax.text(0.006, 0.88, row["company_name"], transform=ax.transAxes,
                fontsize=9, fontweight="bold",
                color=TEXT if verdict else MUTED, va="top")
        if verdict:
            ax.text(0.006, 0.60, verdict.strip(), transform=ax.transAxes, fontsize=8.5,
                    color=RED if not drops.empty else AMBER, va="top", fontweight="bold")

        ax.grid(True, alpha=0.15, linewidth=0.5)
        ax.set_axisbelow(True)
        for spine in ("top", "right"):
            ax.spines[spine].set_visible(False)
        ax.tick_params(labelsize=8)
        ax.set_ylim(bottom=-4)

        zeroes = drops[drops["row_count"] == 0]
        if not zeroes.empty:
            first = zeroes.iloc[0]
            ax.annotate(
                f"extract never ran — {len(zeroes)} days at 0 rows",
                xy=(first["txn_date"], 0),
                xytext=(-210, 26), textcoords="offset points",
                color=RED, fontsize=8.5, fontweight="bold",
                arrowprops=dict(arrowstyle="->", color=RED, lw=1.2),
            )
        if not spikes.empty:
            worst = spikes.loc[spikes["row_count"].idxmax()]
            ax.annotate(
                f"extract ran twice — {worst['row_count']:.0f} rows vs "
                f"{worst['expected']:.0f} expected",
                xy=(worst["txn_date"], worst["row_count"]),
                xytext=(-250, -12), textcoords="offset points",
                color=AMBER, fontsize=8.5, fontweight="bold",
                arrowprops=dict(arrowstyle="->", color=AMBER, lw=1.2),
            )

    fig.suptitle("Daily transaction volume per subsidiary",
                 color=TEXT, fontsize=14, fontweight="bold",
                 x=0.075, ha="left", y=0.997)
    fig.text(0.075, 0.9655,
             "White line is the 28-day rolling median. Every one of the 70 dbt tests "
             "passes on all 5,400 of these company-days, including the three at zero.",
             color=MUTED, fontsize=9, ha="left")
    axes[-1].set_xlabel("transaction date")
    fig.subplots_adjust(top=0.938, hspace=0.12)
    _save(fig, "ml_volume_monitor.png")


# --------------------------------------------------------------------------- 5
def chart_unit_trap(db_path: str = os.path.join("data", "edw.duckdb")) -> None:
    """
    Trap 2, the mixed time units, shown as reported hours before and after the fix.

    This is the most expensive trap in the project and the least visible: work_hours is
    sometimes booked in seconds, with the unit in a separate column. Missing it inflates
    labour by 3,600x on the affected rows, and the total still looks like a number.
    """
    import duckdb

    con = duckdb.connect(db_path, read_only=True)
    df = con.execute(
        """
        select
            c.company_name,
            sum(t.work_hours)             as correct_hours,
            -- The naive figure needs no arithmetic at all: it is simply the as-sourced
            -- column summed, mixing seconds and hours in one total. That is precisely
            -- how the mistake happens in practice -- nobody computes anything wrong,
            -- they just SUM the column that was already there.
            sum(t.work_hours_as_sourced)  as naive_hours,
            sum(t.was_unit_converted)     as rows_in_seconds
        from main_marts.fct_labour_hours t
        join main_marts.dim_company c on t.company_key = c.company_key
        where t.is_deleted = 0
        group by 1
        order by 2 desc
        """
    ).df()
    con.close()

    fig, ax = plt.subplots(figsize=(11, 5.5))
    x = np.arange(len(df))
    width = 0.38

    ax.bar(x - width / 2, df["naive_hours"], width,
           color=RED, alpha=0.9, label="if the unit column is ignored")
    ax.bar(x + width / 2, df["correct_hours"], width,
           color=GREEN, label="after converting seconds to hours")

    ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels([n[:22] for n in df["company_name"]], fontsize=9,
                       rotation=18, ha="right")
    ax.set_ylabel("total labour hours  (log scale)")
    ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:,.0f}"))

    worst = (df["naive_hours"] / df["correct_hours"]).max()
    _style(ax, "Trap 2 — the same query, reported two ways",
           f"Ignoring one unit column overstates labour by up to {worst:,.0f}x. "
           "Both totals look plausible in isolation.")
    ax.legend(facecolor=PANEL, edgecolor=GRID, labelcolor=TEXT, framealpha=0.9)
    _save(fig, "trap_unit_conversion.png")


def main() -> None:
    print("Generating charts from the live pipeline outputs")
    print("-" * 46)

    scored = pd.read_parquet(os.path.join(ML_DIR, "scored_transactions.parquet"))
    pr = pd.read_parquet(os.path.join(ML_DIR, "pr_curve.parquet"))
    daily = pd.read_parquet(os.path.join(ML_DIR, "daily_volume.parquet"))
    with open(os.path.join(ML_DIR, "metrics.json"), encoding="utf-8") as fh:
        metrics = json.load(fh)

    chart_score_distribution(scored, metrics)
    chart_rule_vs_model(metrics)
    chart_pr_curve(pr, metrics)
    chart_volume_monitor(daily)
    chart_unit_trap()

    print("-" * 46)
    print(f"Wrote 5 charts to {OUT_DIR}")
    print("\nNext:  python -m docs.build_report_pdf")


if __name__ == "__main__":
    main()
