"""
Generates docs/data-dictionary.md by reading the built warehouse.

Written as a generator rather than a hand-maintained document for one reason: a hand-written
data dictionary is wrong within a month. Nobody remembers to update it when a column is
added, so it slowly becomes a document that actively misleads people. This one is rebuilt by
`make docs` and cannot drift from the schema it describes.

Column descriptions come from the dbt schema.yml files via manifest.json, so the prose lives
next to the model it documents rather than in a second place that has to be kept in sync.

Usage:
    python -m docs.build_data_dictionary
"""
from __future__ import annotations

import json
import os

import duckdb

DB = os.path.join("data", "edw.duckdb")
MANIFEST = os.path.join("target", "manifest.json")
OUT = os.path.join("docs", "data-dictionary.md")

SCHEMAS = ["main_staging", "main_intermediate", "main_marts"]

LAYER_BLURB = {
    "main_marts": (
        "Dimensional layer. This is what reporting reads. Six conformed dimensions and four "
        "fact tables, all defect-free by construction."
    ),
    "main_intermediate": (
        "Reshaping layer. Unions the three incompatible time-entry sources onto one grain "
        "and aggregates bookings before they reach the variance fact."
    ),
    "main_staging": (
        "Cleaning layer. Every one of the ten data traps is resolved here, exactly once. "
        "Nothing downstream repeats this work."
    ),
}


def load_descriptions() -> dict[tuple[str, str], str]:
    """Pulls column descriptions out of the dbt manifest, keyed on (model, column)."""
    if not os.path.exists(MANIFEST):
        return {}
    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)

    out: dict[tuple[str, str], str] = {}
    for node in manifest.get("nodes", {}).values():
        if node.get("resource_type") != "model":
            continue
        name = node["name"]
        for col, meta in (node.get("columns") or {}).items():
            desc = (meta.get("description") or "").strip().replace("\n", " ")
            if desc:
                out[(name, col.lower())] = desc
    return out


def model_descriptions() -> dict[str, str]:
    if not os.path.exists(MANIFEST):
        return {}
    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)
    return {
        node["name"]: (node.get("description") or "").strip().replace("\n", " ")
        for node in manifest.get("nodes", {}).values()
        if node.get("resource_type") == "model"
    }


def main() -> None:
    if not os.path.exists(DB):
        raise SystemExit(f"{DB} not found. Run the build first -- see docs/runbook.md.")

    col_desc = load_descriptions()
    mod_desc = model_descriptions()
    con = duckdb.connect(DB, read_only=True)

    lines: list[str] = [
        "# Data dictionary",
        "",
        "**Generated by `python -m docs.build_data_dictionary` from the built warehouse.**",
        "Do not edit by hand -- rerun `make docs` instead.",
        "",
        "A hand-maintained dictionary is wrong within a month, because nobody remembers to",
        "update it when a column is added. This one is read straight from the schema, and the",
        "prose comes from the dbt `schema.yml` files, so it cannot disagree with the models.",
        "",
        "---",
        "",
    ]

    # Summary table first, so the document is navigable.
    lines += ["## Contents", "", "| Layer | Object | Rows | Columns |", "|---|---|---:|---:|"]
    inventory: dict[str, list[tuple[str, int, int]]] = {}
    for schema in SCHEMAS:
        tables = [
            r[0] for r in con.execute(
                "select table_name from information_schema.tables "
                "where table_schema = ? order by table_name", [schema]
            ).fetchall()
        ]
        inventory[schema] = []
        for t in tables:
            n = con.execute(f'select count(*) from {schema}."{t}"').fetchone()[0]
            cols = con.execute(f'describe {schema}."{t}"').fetchall()
            inventory[schema].append((t, n, len(cols)))
            lines.append(f"| `{schema}` | [`{t}`](#{t.replace('_', '-')}) | {n:,} | {len(cols)} |")
    lines += ["", "---", ""]

    for schema in reversed(SCHEMAS):        # marts first; it is what people want
        lines += [f"## {schema}", "", LAYER_BLURB.get(schema, ""), ""]
        for table, n, _ncols in inventory[schema]:
            lines += [f"### {table}", ""]
            if mod_desc.get(table):
                lines += [mod_desc[table], ""]
            lines += [f"`{schema}.{table}` — **{n:,} rows**", ""]
            lines += ["| Column | Type | Description |", "|---|---|---|"]
            for row in con.execute(f'describe {schema}."{table}"').fetchall():
                col, dtype = row[0], row[1]
                desc = col_desc.get((table, col.lower()), "")
                lines.append(f"| `{col}` | `{dtype}` | {desc} |")
            lines.append("")
        lines += ["---", ""]

    # The label schema, documented explicitly because its isolation is a design decision.
    try:
        n = con.execute("select count(*) from ml.defect_labels").fetchone()[0]
        lines += [
            "## ml  (ground truth, not part of the warehouse)",
            "",
            "Deliberately **not declared in `sources.yml`**, so no dbt model can reference it "
            "even accidentally. The warehouse is built without ever seeing which rows are "
            "defective; these labels exist only to score detection afterwards. On a real "
            "platform this is where your confirmed incident log lives.",
            "",
            f"`ml.defect_labels` — **{n:,} rows**",
            "",
            "| Column | Type | Description |",
            "|---|---|---|",
        ]
        notes = {
            "defect_type": "CORRUPT_QUANTITY, CONTEXTUAL_PRICE, EPOCH_DATE or SOURCE_DUPLICATE",
            "quantity": "part of the join key: passes through staging unchanged, unlike the timestamp",
            "unit_cost": "part of the join key, for the same reason",
        }
        for row in con.execute("describe ml.defect_labels").fetchall():
            lines.append(f"| `{row[0]}` | `{row[1]}` | {notes.get(row[0], '')} |")
        lines += [""]

        lines += ["### Label counts", "", "| Defect type | Rows |", "|---|---:|"]
        for defect, count in con.execute(
            "select defect_type, count(*) from ml.defect_labels "
            "group by 1 order by 2 desc"
        ).fetchall():
            lines.append(f"| `{defect}` | {count:,} |")
        lines += [""]
    except duckdb.CatalogException:
        pass

    con.close()

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")

    total = sum(n for rows in inventory.values() for _t, n, _c in rows)
    print(f"Wrote {OUT}")
    print(f"  {sum(len(v) for v in inventory.values())} objects, {total:,} rows documented")


if __name__ == "__main__":
    main()
